language: php

php:
  - 7.0

before_script:
  - mysql -e 'create database symfony'
  - cp app/config/parameters.travis.yml app/config/parameters.yml
  - composer install
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - php vendor/bin/behat