# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sowp_news_module_upload_path: "%kernel.root_dir%/../web/upload/news_attachments"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#  gedmo.listener.softdeleteable:
#    class: Gedmo\SoftDeleteable\SoftDeleteableListener
#    tags:
#        - { name: doctrine.event_subscriber, connection: default }
#    calls:
#        - [ setAnnotationReader, [ @annotation_reader ] ]

#    news_module.attachment_upload:
#        class: Sowp\NewsModuleBundle\EventListener\Doctrine\AttachmentUploadListener
#        arguments: [ '%upload_path%' ]
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }

    sowp.news.form.transform.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments: ['@exercise_html_purifier.default']

    sowp.news.form.type.purified_textarea:
        class: Sowp\NewsModuleBundle\Form\TinyMceType
        arguments: ['@sowp.news.form.transform.html_purifier']
        tags:
            - { name: form.type }

    news_module.dashboard_provider:
        class: Sowp\NewsModuleBundle\DashboardProvider\NewsDashboardProvider
        arguments: ['@router']
        tags:
            - { name: sowp.dashboard.element_provider }

    sowp.news.search_result_provider.orm:
        class: Sowp\NewsModuleBundle\SearchProvider\SearchProvider
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: sowp.bip.search_result_provider.orm }

    sowp.news.Search_template_provider:
        class: Sowp\NewsModuleBundle\SearchProvider\SearchTemplateProvider
        tags:
            - { name: sowp.bip.search_template }

    sowp.news.form.test_type:
        class: Sowp\NewsModuleBundle\Form\TestType
        arguments: ['@sowp.news.form.transform.html_purifier']
        tags:
            - { name: form.type}

