<?php

namespace Sowp\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findAllQueryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        return $qb->select('a')->from(Article::class, 'a');
    }

    public function findAllQuery()
    {
        return $this->findAllQueryBuilder()->getQuery();
    }

    public function findDeletedQueryBuilder()
    {
        $em = $this->getEntityManager();

        $now = new \DateTime('now');

        $qb = $em->createQueryBuilder();
        $qb = $qb->select('a')
            ->from(Article::class, 'a')
            ->where('a.deletedAt < ?1')
            ->setParameter(1, $now);

        return $qb;
    }

    public function findDeletedQuery()
    {
        return $this->findDeletedQueryBuilder()->getQuery();
    }

    public function findDeleted()
    {
        return $this->findDeletedQuery()->getResult();
    }

    public function findPublishedQueryBuilder()
    {
        $em = $this->getEntityManager();

        $now = new \DateTime('now');

        $qb = $em->createQueryBuilder();
        $qb = $qb->select('a')
            ->from(Article::class, 'a')
            ->where('a.deletedAt > ?1')
            ->orWhere('a.deletedAt IS NULL')
            ->setParameter(1, $now);

        return $qb;
    }

    public function findPublishedQuery()
    {
        return $this->findPublishedQueryBuilder()->getQuery();
    }

    public function findPublished()
    {
        return $this->findPublishedQuery()->getResult();
    }
}
