<?php

namespace Sowp\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Sortable\Entity\Repository\SortableRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Gedmo\Tree\Strategy\ORM\Nested;
use Mapping\Fixture\Xml\NestedTree;

/**
 * MenuItemRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends NestedTreeRepository
{
    public function getDynamicItemsOnly()
    {
        $qb = $this->createQueryBuilder('items');
        return $qb->where($qb->expr()->isNotNull('items.object_clazz'))
            ->getQuery()
            ->getResult();
    }
}
