<?php

namespace Sowp\RegistryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ValueRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ValueRepository extends EntityRepository
{
}
